let db, chapter=+(localStorage.getItem('faChapter')||1), archive=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
fetch('archive.json').then(r=>r.json()).then(x=>{db=x; $('#chapter').value=chapter; render()});
function visible(x){return archive||x.chapter<=chapter} function pct(){return Math.round(chapter/db.maxChapter*100)}
function render(){
 $('#chapterLabel').textContent=chapter; $('#percent').textContent=String(pct()).padStart(2,'0')+'%';
 const fs=db.ferals.filter(visible), its=db.items.filter(visible), ls=db.locations.filter(visible);
 $('#feralCount').textContent=fs.length+'/'+db.ferals.length; $('#itemCount').textContent=its.length; $('#locCount').textContent=ls.length;
 $('#feed').innerHTML=[...fs.slice(-3).map(x=>`<div class="log"><b>FERAL RECORD // ${x.name.toUpperCase()}</b><span>Roster data available from Chapter ${x.chapter}</span></div>`),...its.slice(-2).map(x=>`<div class="log"><b>ITEM RECORD // ${x.name.toUpperCase()}</b><span>System inventory data acquired</span></div>`)].reverse().join('')||'<div class="log"><b>INITIALIZING ARCHIVE</b><span>Awaiting System data...</span></div>';
 renderDex(); renderItems(); renderMap();
}
function renderDex(){let q=($('#search')?.value||'').toLowerCase(); let list=db.ferals.filter(x=>x.name.toLowerCase().includes(q)||x.type.toLowerCase().includes(q)||x.feralClass.toLowerCase().includes(q)); $('#rosterTotal').textContent=`${db.ferals.length} ROSTER SLOTS`; $('#feralGrid').innerHTML=list.map(x=>visible(x)?`<article class="panel card feralCard" data-feral="${x.id}"><small>DEX // CH ${x.chapter}</small><h3>${x.name}</h3><p class="flavorMini">${x.flavor}</p><div class="tags"><span class="tag">${x.type}</span><span class="tag">${x.feralClass}</span></div><div class="meta">${x.level?'LEVEL '+x.level:'LEVEL DATA VARIABLE'} • ${x.role}</div></article>`:`<article class="panel card locked"><small>UNDISCOVERED // CHAPTER ${x.chapter}</small><h3>UNKNOWN FERAL</h3><div class="silhouette">?</div><div class="tags"><span class="tag">DATA SEALED</span></div></article>`).join(''); $$('[data-feral]').forEach(e=>e.onclick=()=>openFeral(e.dataset.feral))}
function renderItems(){ $('#itemGrid').innerHTML=db.items.map(x=>visible(x)?`<article class="panel card"><small>${x.category.toUpperCase()} // CH ${x.chapter}</small><h3>${x.name}</h3><p>${x.description}</p></article>`:`<article class="panel card locked"><small>UNDISCOVERED ITEM // CH ${x.chapter}</small><h3>SEALED RECORD</h3></article>`).join('') }
function renderMap(){let pos=[[18,20],[68,28],[28,72],[72,68],[48,18]]; $('#nodes').innerHTML=db.locations.map((x,i)=>visible(x)?`<span class="node" style="left:${pos[i%pos.length][0]}%;top:${pos[i%pos.length][1]}%">${x.name.toUpperCase()}</span>`:'').join('')}
function openFeral(id){let x=db.ferals.find(f=>f.id===id); let abs=(x.abilities||[]).length?x.abilities.map(a=>`<span class="ability">${a}</span>`).join(''):'<span class="muted">No named abilities archived at first encounter.</span>'; $('#modalBody').innerHTML=`<small>SYSTEM DEX // FERAL RECORD</small><h2>${x.name}</h2><div class="scanline"></div><p class="dexFlavor">${x.flavor}</p><div class="statgrid"><div><small>HEIGHT*</small><b>${x.height}</b></div><div><small>WEIGHT*</small><b>${x.weight}</b></div><div><small>CLASS</small><b>${x.feralClass}</b></div><div><small>LEVEL</small><b>${x.level||'Variable'}</b></div><div><small>THREAT*</small><b>${x.threat}</b></div><div><small>ROLE*</small><b>${x.role}</b></div></div><p><b>TYPE</b><br>${x.type}</p><p><b>TEMPERAMENT</b><br>${x.temperament||'Not recorded'}</p><p><b>LIKELY HABITAT*</b><br>${x.habitat}</p><p><b>KNOWN ABILITIES</b></p><div class="abilities">${abs}</div><p><b>ARCHIVE NOTES</b><br>${x.notes}</p><small>* DEX ESTIMATE / FLAVOR STAT • FIRST ARCHIVED // BOOK 01 • CHAPTER ${x.chapter}</small>`; $('#modal').classList.add('open')}
$('#chapter').oninput=e=>{chapter=+e.target.value;localStorage.setItem('faChapter',chapter);render()}; $('#search').oninput=renderDex; $('#close').onclick=()=>$('#modal').classList.remove('open'); $('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};
$('#mode').onclick=()=>{if(!archive&&!confirm('ARCHIVE MODE may reveal System data beyond your selected chapter. Continue?'))return; archive=!archive; $('#mode').textContent=archive?'ARCHIVE MODE':'READER MODE';render()};
$$('#nav button').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.remove('active')); $('#'+b.dataset.view).classList.add('active'); $$('#nav button').forEach(x=>x.classList.remove('on')); b.classList.add('on'); window.scrollTo(0,0)});
